{{- if and .Values.frontend.enabled .Values.frontend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    haproxy.router.openshift.io/timeout: 24h
spec:
  host: {{ .Values.frontend.route.host }}
  to:
    kind: Service
    name: {{ .Values.appName }}-frontend
    weight: 100
  port:
    targetPort: http
  {{- if .Values.frontend.route.tls.enabled }}
  tls:
    termination: {{ .Values.frontend.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.frontend.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
