{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.appName }}-backend
{{- end }}
