{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-backend
        {{- toYaml .Values.labels | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.port }}
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ .Values.appName }}-backend-config
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: {{ .Values.backend.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.path }}
            port: {{ .Values.backend.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
{{- end }}
