apiVersion: v2
name: ed254-aman-client
description: ED-254 Collaborative AMAN Client - Provider-side dashboard for AMAN operators to manage arrival sequence distribution
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - swim
  - ed254
  - aman
  - aviation
maintainers:
  - name: Marcelo Sales
